### ISSUE TITLE
Doesn't work with intellij 2016.1

### ISSUE THREAD

**Issue by axos88** [vmunier/scalajs-cross-project-intellij#3]

**Comment by axos88** [comment]
Unknown facet type scala

**Comment by vmunier** [comment]
The aim of this project was to give a workaround when using a cross project along with old versions of the IntelliJ plugin (Scala Plugin prior to v1.3.3).

If you are using IntelliJ 13 or 14 and use the Scala Plugin v1.3.3 (or higher), then you don't need to clone this project, just import your own cross project and everything should work fine.
